find_trending_companies:
  description: >
    Find the topmost trending companies thriving in {sector} by searching latest news. 
    Make sure you use your web search tool for carrying out this task efficiently.
    Find new companies that you have not found before. 
  expected_output: >
    A list of trending companies in {sector}.
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Carry out a thorough, detailed and concise research on the found trending companies.
    Provide detailed analysis of each company in a report by searching online 
  expected_output: >
    A report containing detailed analysis of each company.
  agent: financial_researcher
  context : 
    - find_trending_companies
  output_file: output/trending_companies_analysis_report.json

pick_best_company:
  description: >
    Analyze the research findings and pick the best company for investment.
    Send a push notification to the user with the decision and 1 sentence rationale.
    Then respond with a detailed report on why you chose this company, and which companies were not selected.
  expected_output: >
    The chosen company and why it was chosen; the companies that were not selected and why they were not selected.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
